//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.17929
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

/* this Class is invalid
 * TODO finish
using System;
namespace AssemblyCSharp
{
		public class Colorpicker
		{
				public Colorpicker ()
				{
				}
		}
}
*/
